# Generated by Django 4.2.7 on 2026-05-11 17:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_doctor_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="Адрес страницы"
                    ),
                ),
                ("summary", models.TextField(verbose_name="Краткое описание")),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Подробное описание"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="equipment/", verbose_name="Фото"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
            ],
            options={
                "verbose_name": "Оборудование",
                "verbose_name_plural": "Оборудование",
                "ordering": ["order", "name"],
            },
        ),
    ]
