# Generated by Django 4.2.7 on 2026-05-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="patient_problems",
            field=models.TextField(
                blank=True,
                help_text="Каждая проблема с новой строки.",
                verbose_name="С какими проблемами работает",
            ),
        ),
    ]
