# Generated by Django 4.2.7 on 2026-05-11 18:15

from django.db import migrations, models
import django.db.models.deletion


def sync_patient_problems(apps, schema_editor):
    Doctor = apps.get_model('core', 'Doctor')
    PatientProblem = apps.get_model('core', 'PatientProblem')

    for doctor in Doctor.objects.all():
        titles = [
            line.strip()
            for line in doctor.patient_problems.splitlines()
            if line.strip()
        ]
        for order, title in enumerate(titles, start=1):
            PatientProblem.objects.create(
                doctor=doctor,
                title=title,
                order=order,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_doctor_patient_problems"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientProblem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Проблема")),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="Порядок отображения"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_problem_items",
                        to="core.doctor",
                        verbose_name="Врач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проблема пациента",
                "verbose_name_plural": "Проблемы пациентов",
                "ordering": ["order", "title"],
            },
        ),
        migrations.RunPython(sync_patient_problems, migrations.RunPython.noop),
        migrations.AddField(
            model_name="appointment",
            name="patient_problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.patientproblem",
                verbose_name="Проблема обращения",
            ),
        ),
    ]
